import { BookOpen, Loader2, Sparkles, Target, Users } from "lucide-react";
import { type FC, useEffect, useRef, useState } from "react";
import type { PaperSummary as PaperSummaryType } from "../../shared/schemas/index";
import { Button } from "./ui/button";
import { Tabs, TabsList, TabsTrigger } from "./ui/tabs";

/**
 * コンテンツ表示モード
 * - summary: 要約（事実ベース：この論文は何をしているか）
 * - explanation: 説明文（読者ベース：なぜあなたはこの論文を読むべきか）
 */
type ContentMode = "summary" | "explanation";

/**
 * 生成対象の種類
 * - summary: 要約のみ
 * - explanation: 説明文のみ（既存の要約がある場合に使用）
 * - both: 要約と説明文の両方
 */
export type GenerateTarget = "summary" | "explanation" | "both";

/**
 * PaperSummary コンポーネントのProps
 */
interface PaperSummaryProps {
  /** 論文ID */
  paperId: string;
  /** 要約データ（キャッシュ済みの場合） */
  summary?: PaperSummaryType;
  /** 選択中の言語 */
  selectedLanguage?: "ja" | "en";
  /** ローディング状態 */
  isLoading?: boolean;
  /** 要約生成時のコールバック */
  onGenerate?: (paperId: string, language: "ja" | "en", target: GenerateTarget) => void;
  /** 言語切替時のコールバック */
  onLanguageChange?: (language: "ja" | "en") => void;
  /** 自動要約生成が有効か */
  autoGenerate?: boolean;
}

/**
 * PaperSummary - 論文要約・説明文コンポーネント
 *
 * Design Docsに基づく機能:
 * - 要約テキスト表示（事実ベース：この論文は何をしているか）
 * - 説明文表示（読者ベース：なぜあなたはこの論文を読むべきか）
 * - キーポイント表示
 * - 要約/説明文生成ボタン
 * - 日本語/英語の切り替え
 *
 * Context Engineering + "Why Your Writing Isn't Being Read" の教訓:
 * - 要約だけでは読者の興味を引けない
 * - 読者の問題から始まり、解決策を予告する説明文が必要
 */
export const PaperSummary: FC<PaperSummaryProps> = ({
  paperId,
  summary,
  selectedLanguage = "ja",
  isLoading = false,
  onGenerate,
  onLanguageChange,
  autoGenerate = false,
}) => {
  // 原則1「状態の外部化」: language は親（usePaperSummary）で一元管理
  // このコンポーネントは Controlled Component として振る舞う
  const [contentMode, setContentMode] = useState<ContentMode>("summary");
  /** 自動生成が既に発火したかを追跡（同じ論文で重複発火を防ぐ） */
  const hasAutoGeneratedRef = useRef<string | null>(null);

  /** 説明文が存在するか */
  const hasExplanation = Boolean(summary?.explanation);

  // 自動要約生成: 論文が表示され、要約がなく、自動生成が有効な場合に発火
  useEffect(() => {
    const shouldAutoGenerate =
      autoGenerate &&
      !summary &&
      !isLoading &&
      onGenerate &&
      hasAutoGeneratedRef.current !== paperId;

    if (shouldAutoGenerate) {
      hasAutoGeneratedRef.current = paperId;
      // 自動生成時は説明文も含める
      onGenerate(paperId, selectedLanguage, "both");
    }
  }, [paperId, summary, isLoading, autoGenerate, onGenerate, selectedLanguage]);

  const handleLanguageChange = (value: string) => {
    const newLanguage = value as "ja" | "en";
    onLanguageChange?.(newLanguage);
  };

  const handleContentModeChange = (value: string) => {
    setContentMode(value as ContentMode);
  };

  /**
   * 生成ハンドラー
   * @param target - 生成対象（summary: 要約のみ, explanation: 説明文のみ, both: 両方）
   */
  const handleGenerate = (target: GenerateTarget) => {
    onGenerate?.(paperId, selectedLanguage, target);
  };

  return (
    <div className="space-y-4">
      {/* セクションタイトルと言語切替 */}
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-muted-foreground flex items-center gap-2">
          <Sparkles className="h-4 w-4" />
          AI分析
        </h3>

        <Tabs value={selectedLanguage} onValueChange={handleLanguageChange}>
          <TabsList className="h-8">
            <TabsTrigger value="ja" className="text-xs px-3">
              日本語
            </TabsTrigger>
            <TabsTrigger value="en" className="text-xs px-3">
              English
            </TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {/* ローディング状態 */}
      {isLoading && (
        <div className="flex items-center justify-center py-8 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin mr-2" />
          <span>生成中...</span>
        </div>
      )}

      {/* 要約なしの状態 */}
      {!isLoading && !summary && (
        <div className="flex flex-col items-center justify-center py-6 gap-3">
          <div className="flex gap-2">
            <Button
              onClick={() => handleGenerate("summary")}
              disabled={isLoading}
              variant="outline"
              className="gap-2"
            >
              <BookOpen className="h-4 w-4" />
              要約のみ
            </Button>
            <Button onClick={() => handleGenerate("both")} disabled={isLoading} className="gap-2">
              <Sparkles className="h-4 w-4" />
              要約 + 説明文
            </Button>
          </div>
          <p className="text-xs text-muted-foreground text-center">
            要約: 論文の内容を簡潔にまとめます
            <br />
            説明文: なぜこの論文を読むべきかを解説します
          </p>
        </div>
      )}

      {/* 要約ありの状態 */}
      {!isLoading && summary && (
        <div className="space-y-4">
          {/* コンテンツモード切り替え（説明文がある場合のみ表示） */}
          {hasExplanation && (
            <Tabs value={contentMode} onValueChange={handleContentModeChange}>
              <TabsList className="w-full">
                <TabsTrigger value="summary" className="flex-1 text-xs gap-1">
                  <BookOpen className="h-3 w-3" />
                  要約
                </TabsTrigger>
                <TabsTrigger value="explanation" className="flex-1 text-xs gap-1">
                  <Target className="h-3 w-3" />
                  なぜ読むべきか
                </TabsTrigger>
              </TabsList>
            </Tabs>
          )}

          {/* 要約モード */}
          {contentMode === "summary" && (
            <div className="space-y-4">
              <p className="text-sm leading-relaxed">{summary.summary}</p>

              {summary.keyPoints.length > 0 && (
                <div>
                  <h4 className="text-xs font-medium text-muted-foreground mb-2">キーポイント</h4>
                  <ul className="space-y-1">
                    {summary.keyPoints.map((point) => (
                      <li key={point} className="text-sm flex items-start gap-2">
                        <span className="text-primary">•</span>
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* 説明文がない場合、説明文のみ生成を促す */}
              {!hasExplanation && (
                <div className="pt-2 border-t">
                  <Button
                    onClick={() => handleGenerate("explanation")}
                    disabled={isLoading}
                    variant="ghost"
                    size="sm"
                    className="gap-2 text-muted-foreground hover:text-foreground"
                  >
                    <Target className="h-4 w-4" />
                    なぜ読むべきかを生成
                  </Button>
                </div>
              )}
            </div>
          )}

          {/* 説明文モード */}
          {contentMode === "explanation" && hasExplanation && (
            <div className="space-y-4">
              {/* メイン説明文 */}
              <p className="text-sm leading-relaxed">{summary.explanation}</p>

              {/* 対象読者 */}
              {summary.targetAudience && (
                <div className="flex items-start gap-2 p-3 bg-muted/50 rounded-lg">
                  <Users className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                  <div>
                    <h4 className="text-xs font-medium text-muted-foreground mb-1">対象読者</h4>
                    <p className="text-sm">{summary.targetAudience}</p>
                  </div>
                </div>
              )}

              {/* 読む理由 */}
              {summary.whyRead && (
                <div className="flex items-start gap-2 p-3 bg-primary/5 rounded-lg border border-primary/10">
                  <Sparkles className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                  <div>
                    <h4 className="text-xs font-medium text-muted-foreground mb-1">
                      読むと得られるもの
                    </h4>
                    <p className="text-sm">{summary.whyRead}</p>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
