import { BookOpen, Loader2, Sparkles, Target, Users } from "lucide-react";
import { type FC, Fragment, type ReactNode, useEffect, useRef, useState } from "react";
import type { PaperSummary as PaperSummaryType } from "../../shared/schemas/index";
import { PartialSummaryError } from "../lib/summaryErrors";
import { Button } from "./ui/button";
import { Tabs, TabsList, TabsTrigger } from "./ui/tabs";

/**
 * コンテンツ表示モード
 * - summary: 要約（事実ベース：この論文は何をしているか）
 * - explanation: 説明文（読者ベース：なぜあなたはこの論文を読むべきか）
 */
type ContentMode = "summary" | "explanation";

/**
 * 生成対象の種類
 * - explanation: 説明文のみ（既存の要約がある場合に使用）
 * - both: 要約と説明文の両方
 */
export type GenerateTarget = "explanation" | "both";

/**
 * PaperSummary コンポーネントのProps
 */
interface PaperSummaryProps {
  /** 論文ID */
  paperId: string;
  /** 要約データ（キャッシュ済みの場合） */
  summary?: PaperSummaryType;
  /** 選択中の言語 */
  selectedLanguage?: "ja" | "en";
  /** ローディング状態 */
  isLoading?: boolean;
  /**
   * 直近の生成エラー（生成完了時に失敗として通知する。理由はトーストで伝える）
   * PartialSummaryError の場合は、要約は保存済みで説明文だけが失敗した部分成功として扱う
   */
  error?: Error | null;
  /** 直近に失敗した生成の対象（"explanation" なら説明文だけの生成が失敗した） */
  failedTarget?: GenerateTarget | null;
  /** 要約生成時のコールバック */
  onGenerate?: (paperId: string, language: "ja" | "en", target: GenerateTarget) => void;
  /** 言語切替時のコールバック */
  onLanguageChange?: (language: "ja" | "en") => void;
  /** 自動要約生成が有効か */
  autoGenerate?: boolean;
  /** 原文Abstract表示要素のID（指定時は参照範囲の注記からリンクする） */
  abstractId?: string;
  /** 論文PDFのURL */
  pdfUrl?: string;
  /** arXivページのURL */
  arxivUrl?: string;
}

/**
 * PaperSummary - 論文要約・説明文コンポーネント
 *
 * Design Docsに基づく機能:
 * - 要約テキスト表示（事実ベース：この論文は何をしているか）
 * - 説明文表示（読者ベース：なぜあなたはこの論文を読むべきか）
 * - キーポイント表示
 * - 要約/説明文生成ボタン
 * - 日本語/英語の切り替え
 *
 * Context Engineering + "Why Your Writing Isn't Being Read" の教訓:
 * - 要約だけでは読者の興味を引けない
 * - 読者の問題から始まり、解決策を予告する説明文が必要
 */
export const PaperSummary: FC<PaperSummaryProps> = ({
  paperId,
  summary,
  selectedLanguage = "ja",
  isLoading = false,
  error = null,
  failedTarget = null,
  onGenerate,
  onLanguageChange,
  autoGenerate = false,
  abstractId,
  pdfUrl,
  arxivUrl,
}) => {
  // 原則1「状態の外部化」: language は親（usePaperSummary）で一元管理
  // このコンポーネントは Controlled Component として振る舞う
  const [contentMode, setContentMode] = useState<ContentMode>("summary");
  /** 自動生成が既に発火したかを追跡（同じ論文で重複発火を防ぐ） */
  const hasAutoGeneratedRef = useRef<string | null>(null);

  /** 直前の生成結果（支援技術への完了・部分成功・失敗通知用。次の生成開始・論文や言語の切替で消す） */
  const [generationResult, setGenerationResult] = useState<"success" | "partial" | "error" | null>(
    null
  );
  /** 生成中だった論文・言語（完了・失敗を同じ論文・言語でだけ通知するため） */
  const loadingKeyRef = useRef<string | null>(null);
  const generationKey = `${paperId}:${selectedLanguage}`;

  /** 説明文が存在するか */
  const hasExplanation = Boolean(summary?.explanation);
  /**
   * 要約は保存済みで、説明文の工程だけが失敗したか
   * （「要約 + 説明文」の部分成功と、その後の説明文のみの再試行の失敗を同じ状態として扱う）
   */
  const isPartial =
    error instanceof PartialSummaryError || (Boolean(summary) && failedTarget === "explanation");

  // 同じ論文・言語での生成中 → 完了の遷移でだけ結果を記録する（キャッシュ済み要約の表示や切替では通知しない）
  // 生成中に論文・言語を切り替え、完了後に戻った場合は通知しない（要約の表示とトーストで伝わる）。
  // 戻った時点でまだ生成中なら、その完了・失敗を通知する。
  useEffect(() => {
    if (isLoading) {
      loadingKeyRef.current = generationKey;
      setGenerationResult(null);
      return;
    }
    const result = error ? (isPartial ? "partial" : "error") : "success";
    setGenerationResult(loadingKeyRef.current === generationKey ? result : null);
    loadingKeyRef.current = null;
  }, [isLoading, error, isPartial, generationKey]);

  /** 失敗時に再試行で押すボタン（要約があれば説明文のみの生成ボタンが出る） */
  const retryButtonLabel = summary ? "なぜ読むべきかを生成" : "要約 + 説明文";

  // 自動要約生成: 論文が表示され、要約がなく、自動生成が有効な場合に発火
  useEffect(() => {
    const shouldAutoGenerate =
      autoGenerate &&
      !summary &&
      !isLoading &&
      onGenerate &&
      hasAutoGeneratedRef.current !== paperId;

    if (shouldAutoGenerate) {
      hasAutoGeneratedRef.current = paperId;
      // 自動生成時は説明文も含める
      onGenerate(paperId, selectedLanguage, "both");
    }
  }, [paperId, summary, isLoading, autoGenerate, onGenerate, selectedLanguage]);

  /** 外部リンクのクラス */
  const sourceLinkClassName = "underline hover:text-foreground";
  /** 参照範囲の注記から辿れる原文へのリンク（渡されたものだけを並べる） */
  const sourceLinks: { key: string; node: ReactNode }[] = [];
  if (abstractId) {
    sourceLinks.push({
      key: "abstract",
      node: (
        <a
          href={`#${abstractId}`}
          className={sourceLinkClassName}
          onClick={(e) => {
            // ルーターのURLにフラグメントを残さず、履歴も増やさずにスクロールする
            e.preventDefault();
            document.getElementById(abstractId)?.scrollIntoView();
          }}
        >
          Abstract
        </a>
      ),
    });
  }
  for (const { key, url, label } of [
    { key: "pdf", url: pdfUrl, label: "本文PDF" },
    { key: "arxiv", url: arxivUrl, label: "arXivページ" },
  ]) {
    if (url) {
      sourceLinks.push({
        key,
        node: (
          <a href={url} target="_blank" rel="noopener noreferrer" className={sourceLinkClassName}>
            {label}
            <span className="sr-only">（新しいタブで開く）</span>
          </a>
        ),
      });
    }
  }

  const handleLanguageChange = (value: string) => {
    const newLanguage = value as "ja" | "en";
    onLanguageChange?.(newLanguage);
  };

  const handleContentModeChange = (value: string) => {
    setContentMode(value as ContentMode);
  };

  /**
   * 生成ハンドラー
   * @param target - 生成対象（explanation: 説明文のみ, both: 要約と説明文の両方）
   */
  const handleGenerate = (target: GenerateTarget) => {
    onGenerate?.(paperId, selectedLanguage, target);
  };

  return (
    <div className="space-y-4">
      {/* セクションタイトルと言語切替 */}
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-bold text-muted-foreground flex items-center gap-2">
          <Sparkles className="h-4 w-4" />
          AI要約
        </h3>

        <Tabs value={selectedLanguage} onValueChange={handleLanguageChange}>
          <TabsList className="h-8">
            <TabsTrigger value="ja" className="text-xs px-3">
              日本語
            </TabsTrigger>
            <TabsTrigger value="en" className="text-xs px-3">
              English
            </TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {/* 参照範囲の注記: 生成前後を通じて、AIが何を入力にしたかを明示する */}
      <p className="text-xs text-muted-foreground">
        Abstractから生成。本文・図表は未参照
        {sourceLinks.length > 0 && (
          <>
            {"。原文を確認: "}
            {sourceLinks.map((link, i) => (
              <Fragment key={link.key}>
                {i > 0 && " / "}
                {link.node}
              </Fragment>
            ))}
          </>
        )}
      </p>

      {/*
        生成状態の通知: 開始・完了用と失敗用の live region を常設し、中身だけを差し替える。
        要約本文と失敗理由（トーストで伝える）は含めず、フォーカスも移動しない。
      */}
      <output className="sr-only" aria-live="polite" aria-atomic="true">
        {isLoading
          ? "要約を生成しています"
          : generationResult === "success"
            ? "要約の生成が完了しました"
            : null}
      </output>
      <div className="sr-only" role="alert" aria-atomic="true">
        {!isLoading && generationResult === "error"
          ? `要約を生成できませんでした。「${retryButtonLabel}」ボタンで再試行できます。`
          : !isLoading && generationResult === "partial"
            ? `要約は保存済みです。説明文を生成できませんでした。「${retryButtonLabel}」ボタンで説明文だけを再試行できます。`
            : null}
      </div>

      {/* 生成結果の表示: 部分成功（要約のみ保存）と失敗を、要約の有無だけでなく文言でも区別する */}
      {!isLoading && error && (
        <p className="text-xs text-destructive">
          {isPartial
            ? `要約は保存済みです。説明文は生成できませんでした。「${retryButtonLabel}」で説明文だけを再試行できます。`
            : `生成できませんでした。「${retryButtonLabel}」で再試行できます。`}
        </p>
      )}

      {/* ローディング状態 */}
      {isLoading && (
        <div className="flex items-center justify-center py-8 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin mr-2" />
          <span>生成中...</span>
        </div>
      )}

      {/* 要約なしの状態 */}
      {!isLoading && !summary && (
        <div className="flex flex-col items-center justify-center py-6 gap-3">
          <Button onClick={() => handleGenerate("both")} disabled={isLoading} className="gap-2">
            <Sparkles className="h-4 w-4" />
            要約 + 説明文
          </Button>
          <p className="text-xs text-muted-foreground text-center">
            要約: Abstractの記述を簡潔にまとめます
            <br />
            説明文: Abstractをもとに、この論文を読む理由をAIが推測します
          </p>
        </div>
      )}

      {/* 要約ありの状態 */}
      {!isLoading && summary && (
        <div className="space-y-4">
          {/* コンテンツモード切り替え（説明文がある場合のみ表示） */}
          {hasExplanation && (
            <Tabs value={contentMode} onValueChange={handleContentModeChange}>
              <TabsList className="w-full">
                <TabsTrigger value="summary" className="flex-1 text-xs gap-1">
                  <BookOpen className="h-3 w-3" />
                  要約
                </TabsTrigger>
                <TabsTrigger value="explanation" className="flex-1 text-xs gap-1">
                  <Target className="h-3 w-3" />
                  なぜ読むべきか
                </TabsTrigger>
              </TabsList>
            </Tabs>
          )}

          {/* 要約モード */}
          {contentMode === "summary" && (
            <div className="space-y-4">
              <p className="text-sm leading-relaxed">{summary.summary}</p>

              {summary.keyPoints.length > 0 ? (
                <div>
                  <h4 className="text-xs text-muted-foreground mb-2">キーポイント</h4>
                  <ul className="space-y-1">
                    {summary.keyPoints.map((point) => (
                      <li key={point} className="text-sm flex items-start gap-2">
                        <span className="text-primary">•</span>
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}

              {/* 説明文がない場合、説明文のみ生成を促す */}
              {!hasExplanation && (
                <div className="pt-2 border-t">
                  <Button
                    onClick={() => handleGenerate("explanation")}
                    disabled={isLoading}
                    variant="ghost"
                    size="sm"
                    className="gap-2 text-muted-foreground hover:text-foreground"
                  >
                    <Target className="h-4 w-4" />
                    なぜ読むべきかを生成
                  </Button>
                </div>
              )}
            </div>
          )}

          {/* 説明文モード */}
          {contentMode === "explanation" && hasExplanation && (
            <div className="space-y-4">
              {/* 論文中の事実と区別するための注記 */}
              <p className="text-xs text-muted-foreground">
                以下はAbstractをもとにしたAIの推奨です。論文中の記述ではありません。
              </p>

              {/* メイン説明文 */}
              <p className="text-sm leading-relaxed">{summary.explanation}</p>

              {/* 対象読者 */}
              {summary.targetAudience && (
                <div className="flex items-start gap-2 p-3 bg-muted/50 rounded-lg">
                  <Users className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                  <div>
                    <h4 className="text-xs text-muted-foreground mb-1">対象読者</h4>
                    <p className="text-sm">{summary.targetAudience}</p>
                  </div>
                </div>
              )}

              {/* 読む理由 */}
              {summary.whyRead && (
                <div className="flex items-start gap-2 p-3 bg-primary/5 rounded-lg border border-primary/10">
                  <Sparkles className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                  <div>
                    <h4 className="text-xs text-muted-foreground mb-1">読むと得られるもの</h4>
                    <p className="text-sm">{summary.whyRead}</p>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
